name: Deploy FastAPI App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode AWS SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | base64 -d > private-key.pem
          chmod 600 private-key.pem

      - name: Deploy to EC2 (SSH)
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key_path: private-key.pem
          script: |
            cd fastapi-app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart uvicorn
